### PR TITLE
add load twitter files

### PR DESCRIPTION
**Pull request by tiger12055**
add load_twitter and util for auth twitter account

### CODE REVIEW

**Comment by roanraina** [comment]
I think we should avoid having the consumer_key, consumer_secret, access_token, and access_token_secret publicly in the code. These variables could be stored in a separate credentials or .env file.

**Comment by tiger12055** [comment]
> Member

Addressed

**Comment by roanraina** [comment]
I suggest we do not store the `.env` file in GitHub as they are secretes. We can share this file between collaborators via slack.

**Review by roanraina — APPROVED** [review]
The changes look good! Approved.

**Pull request merged**
